version: "3.7"

services:
  go:
    image: golang:1.22
    volumes:
      - ../:/tkbai-dashboard
      - ./vscode:/root/.vscode-server
      - ./go-build:/root/.cache/go-build
      - ./go-mod:/go/pkg/mod
      - ./bin:/tkbai-dashboard/bin
      - ./pkg:/tkbai-dashboard/pkg
      - /usr/share/zoneinfo/Asia/Jakarta:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /tkbai-dashboard
    command: bash -c "/tkbai-dashboard/docker/initdev.sh"
    ports:
      - 9070:9070

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 03IZmt7eRMukIHdoZahl
      MYSQL_DATABASE: tkbai
      MYSQL_USER: user1
      MYSQL_PASSWORD: 03IZmt7eRMukIHdoZahl
    ports:
      - 7070:3306
    volumes:
      - tkbai_mysql_data:/var/lib/mysql/

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: hSqdQwcX90GGFgpBaT6m
      DB_VENDOR: MYSQL
      DB_ADDR: mysql-keycloak
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: 03IZmt7eRMukIHdoZahl
    depends_on:
      - mysql-keycloak
    #   - traefik
    command: start-dev
    volumes:
      - tkbai_keycloak_data:/opt/jboss/keycloak/standalone/data
    labels:
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"

  mysql-keycloak:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 03IZmt7eRMukIHdoZahl
      MYSQL_DATABASE: keycloak
      MYSQL_USER: user1
      MYSQL_PASSWORD: 03IZmt7eRMukIHdoZahl
    ports:
      - 7071:3306
    volumes:
      - tkbai_mysql_keycloak_data:/var/lib/mysql/
    # depends_on:
    #   - traefik

#   traefik:
#     image: traefik:v2.5
#     container_name: traefik
#     command: --api.insecure=true --providers.docker
#     ports:
#       - "80:80"
#       - "8081:8080"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock

volumes:
  tkbai_go:
    external: true
  tkbai_mysql_data:
    external: true
  tkbai_keycloak_data:
    external: true
  tkbai_mysql_keycloak_data:
    external: true
